#server配置
server:
    port: 80
    #context-path: /SpringBoot_Simp
    
#连接池配置
spring.datasource.initialSize: 5    #初始化时建立物理连接的个数
spring.datasource.minIdle: 5    #最小连接池数量
spring.datasource.maxActive: 20    #最大连接池数量
spring.datasource.maxWait: 60000    #配置获取连接等待超时的时间，单位毫秒
spring.datasource.timeBetweenEvictionRunsMillis: 60000    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.minEvictableIdleTimeMillis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.validationQuery: SELECT 1 FROM DUAL    #用来检测连接是否有效的sql
spring.datasource.testWhileIdle: true    #建议配置为true，不影响性能，并且保证安全性
spring.datasource.testOnBorrow: true    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
spring.datasource.testOnReturn: false    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
spring.datasource.poolPreparedStatements: true    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20    #打开PSCache，并且指定每个连接上PSCache的大小
spring.datasource.filters: stat,wall,log4j    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
spring.datasource.connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'    #通过connectProperties属性来打开mergeSql功能；慢SQL记录

#mybatis配置
mybatis:
  #mapper-locations: com.xinhuanet.mapper
  type-aliases-package: com.xinhuanet.entity

#针对不同环境配置 下面参数会覆盖上面已有的参数 可以在启动时传入参数覆盖此配置  --spring.profiles.active=pro   
spring.profiles.active: dev

---
spring.profiles: dev

config:
    hello: The current application  profile is develop
registry:
    id: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
redis:
    host: 10.123.16.168
    port: 6379
    password: xinhuaDevelop123
    timeout: 100000
ftp:
     ip: 172.21.63.240
     port: 21
     username: xhw
     password: cqLUOO7vRvdHObc5
     maxconnect: 20
     ftptarget: /ftptarget
---
spring.profiles: pro

config:
    hello: The current application  profile is pro
registry:
    id: pro
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
redis:
    host: 10.123.16.168
    port: 6379
    password: xinhuaDevelop123
    timeout: 100000
ftp:
     ip: 172.21.63.240
     port: 21
     username: xhw
     password: cqLUOO7vRvdHObc5
     maxconnect: 20
     ftptarget: /ftptarget

